### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by cbarney** [Lunarelly/PersonaAdapter#1]
I have issues putting this onto my server because it is missing the imagecreatefrompng function. Is this written and not included in the phar file, or still in developement.

**Comment by Lunarelly** [comment]
> I have issues putting this onto my server because it is missing the imagecreatefrompng function. Is this written and not included in the phar file, or still in developement.

It is working only with PHP 8.0+, try to reinstall your binaries from https://jenkins.pmmp.io/job/PHP-8.0-Aggregate/
